### PR TITLE
Supports showing alerts without a window

### PR DESCRIPTION
**Pull request by lijy91**
Solved the following issues

#2 
https://github.com/leanflutter/window_manager/issues/90

### CODE REVIEW

**Comment by zonble** [comment]
Hi @lijy91 

Quick question. Is the fix only applied on macOS? Do we need to care about other platforms?

Thanks!

**Comment by zonble** [comment]
Hi @lijy91 

The Linux build failed. Would you please take a look? Thanks!

**Comment by lijy91** [comment]
> Hi @lijy91
> 
> The Linux build failed. Would you please take a look? Thanks!
> 
> I guess we need to update the CI setting and add a line of "apt-get install appindicator3-0.1 libappindicator3-dev" in the Linux build script.

Fixed.

**Review by zonble — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
